### ISSUE TITLE
Bug: LoaderIO-Endpoint returns 404

### ISSUE THREAD

**Issue by shoutout-team** [shoutout-team/shoutout-app-spa#2]
Expected endpoints:
Upload the file to your server so it is accessible at one of the following URLs:
    http://shoutout-app-spa.herokuapp.com/loaderio-6675f0444ad2b4bc8baefb7958ad98d4/
    http://shoutout-app-spa.herokuapp.com/loaderio-6675f0444ad2b4bc8baefb7958ad98d4.html
    http://shoutout-app-spa.herokuapp.com/loaderio-6675f0444ad2b4bc8baefb7958ad98d4.txt

Working endpoint but without required response-text:
https://shoutout-app-spa.herokuapp.com/loaderio-6675f0444ad2b4bc8baefb7958ad98d4.txt

![grafik](https://user-images.githubusercontent.com/62569026/78083848-f7642900-73b6-11ea-8d15-84c04f6b6e25.png)

**Comment by H3nSte1n** [comment]
done
