### ISSUE TITLE
Bug: Address-Input vs GoogleMaps at SignUp !!!!!

### ISSUE THREAD

**Issue by shoutout-team** [shoutout-team/shoutout-app-spa#21]
Könnt ihr bitte noch mal die gesamte Adresse-Eingabe (für den Desktop) bzgl. allen erdenklichen Benutzerinteraktion QSen. Ich sehe da immer noch gewisse Schwierigkeiten im Handling. Ich teste es nachher noch mal Mobile und werde alle Schritte exakt skizzieren, bei denen ich glaube dass sie zu einem wirklich unerwarteten Verhalten führen. (Desktop ist durchaus relevant!).

Ich habe heute dem Henry im Screen Sharing das Problem live gezeigt und ich denke, er hat es nachvollziehen können und dass sollte dringend behoben werden. Als Quick-Win schlage ich vor, dass ihr die frontend-seitige Validierung entweder runterschraubt (Trust the Backend: ihr bekommt einen 422 mit exakten Validierungsfehlerm) oder zumindest bei einem Problem mit der Adresse auch das Adressfeld entsprechend markiert. Aktuell springt der Screen nur nach oben und zeigt das konkrete Problem überhaupt gar nicht an. D.h. der User sieht zwar eine korrekt eingegebe Adresse, aber kann sich dennoch mangels visuellen Feedback nicht registrieren. (absoluter ShowStopper!)

Meine Vermutung ist, dass ihr einen State von Google Maps in einer Variablen speichert und diese nicht gegen die manuelle Benutzer-Eingabe cross-evaluiert wird. Das führt dazu, dass trotz einer korrekten Adresseeingabe in das Input-Field, dennoch keine Registrierung möglich ist. (Da gar kein visuelles Feedback!). 

Ich würde als FastFix gegebenfalls die Unterstützung (durch Google Maps) bei der Adresseingabe komplett deaktivieren, d.h. stellt für alle Adressfelder auch Input-Fields (Straße, Hausnummer, Postleitzahl, Stadt) zur Verfügung und ermittelt die Geokoordinaten im Hintergrund auf Basis dieser manuellen Adresse-Eingabe (via Google Maps). Das ist immer noch besser, als sich nicht registrieren zu können.

Ihr könnt dann later on in Ruhe euer Google Maps Feature, bezüglich der Eingabeunterstützung bei der Adresse, im Nachgang noch mal genauer analysieren und evaluieren und UX-technisch fixen. Cheers!

**Comment by H3nSte1n** [comment]
done
