### ISSUE TITLE
Editing a company prefills address with maybe current location?

### ISSUE THREAD

**Issue by shoutout-team** [shoutout-team/shoutout-app-spa#7]
Steps:
- As a logged in member, click 'My Profile' for editing 
- Now I have a strange address in my address-field, no matter what is stored in backend

![grafik](https://user-images.githubusercontent.com/62569026/78280703-c94b2a00-7519-11ea-9452-bd47452ea035.png)

![grafik](https://user-images.githubusercontent.com/62569026/78280760-e1bb4480-7519-11ea-8bf7-880cf6a0ed8b.png)

**Comment by H3nSte1n** [comment]
Fixed
